"""message

Revision ID: ee2648b03a1a
Revises: 2b3089910feb
Create Date: 2024-07-01 14:41:51.643630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2648b03a1a'
down_revision = '2b3089910feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
